backend:
  name: github
  repo: yacosta738/blastkode
  branch: main

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"
site_url: https://blastkode.com
display_url: https://blastkode.com
logo_url: https://blastkode.com/logo.svg
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/blog/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Post"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Language"
        name: "lang"
        widget: "select"
        options: [ "en", "es" ]
        default: "en"
      - { label: "Path ( must start with / )", name: "path", widget: "string", default: "/" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "cover", widget: "image", required: false }
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [ "name" ]
        value_field: "name"
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: [ "IT" ] }
      - { label: "Categories", name: "categories", widget: "list", allow_add: true, default: [ "IT" ] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
  - name: "spanish_post"
    label: "Artículos"
    folder: "content/blog/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Artículo"
    fields:
      - { label: "Título'", name: "title", widget: "string" }
      - label: "Idioma"
        name: "lang"
        widget: "select"
        options: [ "en", "es" ]
        default: "en"
      - { label: "Ruta ( debe comenzar con / )", name: "path", widget: "string", default: "/" }
      - { label: "Resumen", name: "summary", widget: "string" }
      - { label: "Fecha de publication", name: "date", widget: "datetime" }
      - { label: "Imagen de Cover", name: "cover", widget: "image", required: false }
      - label: "Autor del Artículo"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: [ "name" ]
        value_field: "name"
      - { label: "Cuerpo", name: "body", widget: "markdown" }
      - { label: "Etiquetas", name: "tags", widget: "list", allow_add: true, default: [ "IT" ] }
      - { label: "Categorías", name: "categories", widget: "list", allow_add: true, default: [ "IT" ] }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    label_singular: "Author"
    folder: "content/authors/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: title
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Rol", name: "rol", widget: "string" }
      - label: "Language"
        name: "lang"
        widget: "select"
        options: [ "en", "es"]
        default: "en"
      - { label: "Author image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "string" }
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - label: "Icon"
            name: "icon"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Contact"
        name: "contact_items"
        widget: "list"
        fields:
          - label: "Icon"
            name: "icon"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Value", name: "value", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
          - { label: "Text", name: "text", widget: "string" }
          - label: "Target"
            name: "target"
            widget: "select"
            options: [ "_blank", "_self",  "_parent", "_top", "framename" ]
            default: "_blank"
      - label: "Resume"
        name: "resume"
        widget: "list"
        fields:
          - label: "Experience"
            name: "experience"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - label: "Icon"
                    name: "icon"
                    widget: "object"
                    fields:
                      - { label: "Type", name: "type", widget: "string" }
                      - { label: "Value", name: "value", widget: "string" }
                  - { label: "Start Date", name: "start_date", widget: "datetime" }
                  - { label: "End Date", name: "end_date", widget: "datetime" }
                  - { label: "Location", name: "location", widget: "string" }
                  - { label: "Main activities and responsibilities", name: "main_activities", widget: "markdown", minimal: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "autores" # Used in routes, e.g., /admin/collections/blog
    label: "Autores" # Used in the UI
    label_singular: "Autor"
    folder: "content/authors/es" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: title
    fields: # The fields for each document, usually in front matter
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Rol", name: "role", widget: "string" }
      - label: "Idioma"
        name: "lang"
        widget: "select"
        options: [ "en", "es"]
        default: "en"
      - { label: "Imagen del Autor", name: "image", widget: "image", required: false }
      - { label: "Resumen", name: "summary", widget: "string" }
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - label: "Icono"
            name: "icon"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Tipo", name: "type", widget: "string" }
              - { label: "Valor", name: "value", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Contacto"
        name: "contact_items"
        widget: "list"
        fields:
          - label: "Icono"
            name: "icon"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Tipo", name: "type", widget: "string" }
              - { label: "Valor", name: "value", widget: "string" }
          - { label: "Nombre", name: "name", widget: "string" }
          - { label: "Enlace", name: "link", widget: "string" }
          - { label: "Texto", name: "text", widget: "string" }
          - label: "Target"
            name: "target"
            widget: "select"
            options: [ "_blank", "_self",  "_parent", "_top", "framename" ]
            default: "_blank"
      - label: "Resumen"
        name: "resume"
        widget: "list"
        fields:
          - label: "Experiencia"
            name: "experience"
            widget: "object"
            collapsed: false
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - label: "Elementos"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Nombre", name: "name", widget: "string" }
                  - label: "Icono"
                    name: "icon"
                    widget: "object"
                    fields:
                      - { label: "Tipo", name: "type", widget: "string" }
                      - { label: "Valor", name: "value", widget: "string" }
                  - { label: "Fecha inicial", name: "start_date", widget: "datetime" }
                  - { label: "Fecha final", name: "end_date", widget: "datetime" }
                  - { label: "Ubicación", name: "location", widget: "string" }
                  - { label: "Actividades principales y responsabilidades", name: "main_activities", widget: "markdown", minimal: true }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Job"
    filter: {field: "lang", value: "en"}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Language"
        name: "lang"
        widget: "select"
        options: [ "en", "es"]
        default: "en"
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Start Date", name: "start_date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "trabajos"
    label: "Trabajos"
    folder: "content/jobs/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Trabajo"
    filter: { field: "lang", value: "es" }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Idioma"
        name: "lang"
        widget: "select"
        options: [ "en", "es"]
        default: "en"
      - { label: "Rol", name: "role", widget: "string" }
      - { label: "Empresa", name: "company", widget: "string" }
      - { label: "Ubicación", name: "location", widget: "string" }
      - { label: "Fecha Inicial", name: "start_date", widget: "datetime" }
      - { label: "Fecha Final", name: "end_date", widget: "datetime" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "content/projects/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Project"
    filter: { field: "lang", value: "en" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Language"
        name: "lang"
        widget: "select"
        options: [ "en", "es" ]
        default: "en"
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Github", name: "github", widget: "string", required: false }
      - { label: "External", name: "external", widget: "string", required: false }
      - { label: "IOS", name: "ios", widget: "string", required: false }
      - { label: "Android", name: "android", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string" }
      - label: "Technologies"
        name: "tech"
        widget: "relation"
        collection: "technologies"
        multiple: true
        file: "tech"
        search_fields: ["tech.*.name"]
        display_fields: ["tech.*.name"]
        value_field: "tech.*.id"
      - { label: "Show in Projects", name: "showInProjects", widget: "boolean", default: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "proyectos"
    label: "Proyectos"
    folder: "content/projects/es"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    label_singular: "Proyecto"
    filter: { field: "lang", value: "es" }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Idioma"
        name: "lang"
        widget: "select"
        options: [ "en", "es" ]
        default: "en"
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Github", name: "github", widget: "string", required: false }
      - { label: "Externo", name: "external", widget: "string", required: false }
      - { label: "IOS", name: "ios", widget: "string", required: false }
      - { label: "Android", name: "android", widget: "string", required: false }
      - { label: "Empresa", name: "company", widget: "string" }
      - label: "Technologies"
        name: "tech"
        widget: "relation"
        collection: "technologies"
        multiple: true
        file: "tech"
        search_fields: ["tech.*.name"]
        display_fields: ["tech.*.name"]
        value_field: "tech.*.id"
      - { label: "Show in Projects", name: "showInProjects", widget: "boolean", default: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "technologies"
    label: "Technologies"
    extension: json
    files:
      - label: "tech"
        name: "tech"
        file: "src/data/tech.json"
        fields:
          - label: "tech"
            name: "tech"
            widget: "list"
            fields:
              - { label: "id", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - label: "Icon"
                name: "icon"
                widget: "object"
                required: false
                fields:
                  - { label: "Type", name: "type", widget: "string" }
                  - { label: "Value", name: "value", widget: "string" }
              - { label: "URL", name: "url", widget: "string", required: false }
